name: Continuous Integration
on: [push]                      # Will make the workflow run every time you push to any branch

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    steps:
    - uses: actions/checkout@v4 # Adds a step to checkout the repository code

    - name: Build C# code
      run: dotnet build

    - name: Run C# tests
      run: dotnet test

    - name: Build TypeScript code
      run: | 
        cd DotnetTemplate.Web
        npm install
        npm run build

    - name: Run TypeScript linter
      run: | 
        cd DotnetTemplate.Web
        npm run lint

    - name: Run TypeScript tests
      run: | 
        cd DotnetTemplate.Web
        npm test

    - name: Send GitHub Action failure notification to Slack channel
      if: failure()
      uses: slackapi/slack-github-action@v1.26.0
      with:
        payload: |
          {
            "username": "GitHub Actions"
            "text": "GitHub Action failed",
            "icon_emoji": ":cross:"
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    - name: Send GitHub Action success notification to Slack channel
      if: success()
      uses: slackapi/slack-github-action@v1.26.0
      with:
        payload: |
          {
            "username": "GitHub Actions"
            "text": "GitHub Action succeeded",
            "icon_emoji": ":tick:"
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    - name: Send GitHub Action cancelled notification to Slack channel
      if: cancelled()
      uses: slackapi/slack-github-action@v1.26.0
      with:
        payload: |
          {
            "username": "GitHub Actions"
            "text": "GitHub Action cancelled by ${{github.actor}}",
            "icon_emoji": ":warning:"
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}